name: hello_hasteh
description: Example app for Hasteh framework
version: 0.1.0
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  hasteh_core:
    path: ../packages/hasteh_core
  hasteh_http:
    path: ../packages/hasteh_http
